### ISSUE TITLE
All customised settings are lost on TBB update

### ISSUE THREAD

**Issue by axelsimon** [micahflee/torbrowser-launcher#156]
Hi,

It appears any and all customisations that may have been made to the Tor Browser Bundle downloaded by torbrowser-launcher are lost when torbrowser-launcher updates the TBB to a new version.
I understand how as a default, this makes sense, to avoid people messing up/clogging up their copy of the TBB and start having customisations that may de-anonymise them.

However, this means any bookmarks or any extra add-ons (gestures, request policy, adblock, etc.) not only need to be reinstalled on every update but also are lost without warning.

2 suggestions:
- warn users that any customisations made to the TBB downloaded through torbrowser-launcher will be lost on TBB update (ie: often)
- maybe offer a setting to allow to keep extra add-ons, bookmarks, etc. In essence, rather than removing the local profile and replacing it with a fresh one on update, only overwrite the relevant bits of the local firefox TBB profile and keep the rest of it.

In any case, thanks for your work Micah.

Cheers

axel

**Comment by genodeftest** [comment]
The original TBB does not have this issue. IT is introduced by the fact (feature) that torbrowser-launcher does the updates itself.

A possible resolution to this issue could look like this:
Let torbrowser-launcher preferences provide an option to not update torbrowser. Instead torbrowser will update itself. It could be done like this:
[ ] Keep configuration and let torbrowser update itself
I can even think of making this the default.

This change would have effects on usability and security:
* usability: User does not need to wait for torbrowser-launcher to download and install the update. Improves user experience.
* security: Since the update is not applied before starting torbrowser-launcher the user might run an outdated version of TBB for a little longer.

**Comment by micahflee** [comment]
I've just implemented #198 which means that actually customized settings will in fact remain, now that Tor Browser itself handles updates rather than Tor Browser Launcher.
