### ISSUE TITLE
tries to upgrade to 4.5a3

### ISSUE THREAD

**Issue by weaselp** [micahflee/torbrowser-launcher#169]
torbrowser-launcher 0.1.9-1~experimental1 tries to upgrade my tb from 4.0.3 to 4.5a3:

![screenshot](https://cloud.githubusercontent.com/assets/3093718/5955291/c08e5c0c-a7a1-11e4-9dc4-2c251f336752.png)

**Comment by h01ger** [comment]
(that's the stock 0.1.9-1, just called "experimental" as thats where I uploaded it as I had some doubts whether its ready for sid+jessie...)

**Comment by h01ger** [comment]
as just explained in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=775891#35
Hi,

this bug is gone, but users users might be affected from a fall-out from it:
upgrades to alpha/beta versions have appearantly modified the the users config 
to prefer such releases, so that even with newer versions this bug seems still 
to be there, while indeed the bug is now in the user's configuration files.

As there is not really a way to find out if this change was done by bug or on 
purpose, the user has to cleanup her configs manually.

To remove the config manually:

        rm ~/.config/torbrowser/ -r


Thus leaving this bug closed now :)


cheers,
        Holger

**Comment by micahflee** [comment]
Yes, this is fixed.
