### ISSUE TITLE
torbrowser-launcher v tor browser autoupdate

### ISSUE THREAD

**Issue by grrrrr** [micahflee/torbrowser-launcher#198]
Good morning 

Today I got the expected "your browser is out of date" when I launched tbb from `torbrowser-launcher`.  I then went off for a few minutes and when returned I was prompted with a message that the update had downloaded and a restart of tbb would install it.

Obviously TBB does not know it is being managed by `torbrowser-launcher`  but I wonder how is the best way to handle this? I would like to continue using `torbrowser-launcher` as it has gpg sig checking and updates over Tor but realistically the TBB built in autoupdate is nearly always going to beat the launcher to the update.

The current update does not appear to have affected launcher managed TBB and `torbrowser-launcher` detects that TBB is at the most recent after I forced launcher to do a check.

Is there much issue in letting the two fight it out for access, what's the future for `torbrowser-launcher` if there is?

**Comment by grrrrr** [comment]
i tell a lie.  looking at `~/.config/torbrowser/settings`  it says installed ver is `5.0.2` despite tbb reporting `5.0.3`  so there is a disconnect somewhere

**Comment by adrelanos** [comment]
[tb-updater](https://github.com/Whonix/tb-updater) (a Tor Browser downloader, similar to torbrowser-launcher), had the same issue. This is how we decided to more or less solve it:

* renamed `updater` to `downloader`
* deprecated local version number detection (https://phabricator.whonix.org/T400)
* recommend using Tor Browser's internal updater once TBB has been initially downloaded for most cases (except clean re-installation)
* explain all this to the user

See also this screenshot:
![image](https://phabricator.whonix.org/file/data/epd4vbnqym63tajhww7p/PHID-FILE-fluqfju3qgvt7hv5wbvx/tb_updater_local_version_numer_detection_not_implemented.png)

**Comment by micahflee** [comment]
@grrrrr you make a great point that I've been thinking about too. TBL is not needed nearly as much as it used to be now that Tor Browser autoupdates, and now they the Linux version includes a .desktop file so you can launch it entirely from the GUI.

In terms of your specific case, it's actually totally fine to use the built-in Tor Browser auto-updater in conjunction with TBL. if you go ahead and update using the built-in updater, and TBL also discovers that an update is required, it will detect that you're already using that version and just launch it rather than trying to update again. TBL only checks for updates at most once every 24 hours, not every time you launch it. So you must have launched it within the 24 hour window before an update, and it didn't find anything new. Then you launched it again after the update, but TBL skipped checking for updates because it checked so recently.

@adrelanos I actually really like this solution! TBL constantly breaks because of changes in the RecommendedTBBVersions file, or changes in Tor Browser itself (like renaming/moving the `start-tor-browser` script). This will be way less of a problem if TBL only needs to do this on new systems that don't have Tor Browser installed yet, rather than with every launch.

And on a side-note @adrelanos, I actually rarely use TBL myself anymore because most of my Tor Browser usage is in Whonix workstations, so I end up using tb-updater instead. :+1:

**Comment by ToBeReplaced** [comment]
So, I still use this package, but maybe it is time for a change in scope? It seems that the primary purpose now is to download Tor Browser for-the-first-time. I would be interested in a package that pegs 5.0 with baked in checksums and gpg keys, downloads the browser, installs its .desktop file, then gets out of the way. This would be more future-proof and in-line with how the Tor Project wants upgrades to be handled.

Like TBL, this would still hand off trust to the system's package manager. For my use-case, and I imagine many others, this is an acceptable choice.

**Comment by micahflee** [comment]
I don't think it makes sense to peg to the 5.0 release. Like, maybe the autoupgrade feature won't be able to upgrade from 5.0 to 7.0 (or whatever), and I can foresee other problems related to pegging to a specific version.

But I do think it makes sense to install the latest Tor Browser once, and then get out of the way.

**Comment by ToBeReplaced** [comment]
I'd probably seek clarity from Tor Project on what they foresee for the autoupgrade before making a decision. I like that pegging to a release pushes more of the upgrade burden on Tor Project. I don't have an understanding of the nuances around pegging though.

Also, it seems like you'd still need your own .desktop file... so maybe in the absence of pegging all we're really talking about is removing the update features from TBL?

**Comment by micahflee** [comment]
Here's my plan:

TBL will download Tor Browser if it's not installed, and otherwise it will launch it. No more checking for updates. It will only detect the latest version if Tor Browser isn't installed, so it can download and install it.

This will require changing the settings around a lot:

* It should tell you if Tor Browser is installed or not, but no need to keep track of which version is installed anymore.
* Also no need to keep track of the last time it checked for updates.
* Rename `Download updates over Tor (recommended)` to `Download over Tor`, and default it to unchecked (#188).
* Get rid of `Check for updates next launch` options.
* Add a `Reinstall Tor Browser` button, which should the currently installed Tor Browser and re-download it.
