### ISSUE TITLE
Implement option to route all traffic through Tor

### ISSUE THREAD

**Issue by SecUpwN** [micahflee/torbrowser-launcher#223]
Good evening @micahflee, I am currently having a hard time configuring [toriptables2](https://github.com/ruped24/toriptables2) by @ruped24 to run on my [openSUSE Tumbleweed](https://en.opensuse.org/Portal:Tumbleweed). Luckily, @ruped24 is providing awesome support for his script in my Issue https://github.com/ruped24/toriptables2/issues/1. I have seen that several similar projects like `toriptables2` exist on GitHub, but the *ultimate* solution would be if your `torbrowser-launcher` would just feature another option to routre all traffic through Tor. Please consider adding it (maybe even with the funky help of  @ruped24), you guys would a great job against mass surveillance and I am sure many users would love your work!

**Comment by micahflee** [comment]
Thank you! And interesting idea, though I don't think that `torbrowser-launcher` is the best project to include this feature in.

If you want all of your traffic to go through Tor, it seems like it makes the most sense to use a system Tor instead of Tor Browser -- or, better yet, use virtualization such as [Whonix](https://www.whonix.org/). If you run your software in a VM that basically has a Tor router as its network gateway, then you can remain anonymous even if a client (such as Tor Browser) gets hacked.
