### ISSUE TITLE
Please don't execute GnuPG directly

### ISSUE THREAD

**Issue by teythoon** [micahflee/torbrowser-launcher#262]
I ran into #260 (aka #261) yesterday, and noticed that the scary popup box spoke of either an attack or a network error, while the reason was actually the missing key.

The problem here is (from my pov as GnuPG developer), that you are calling gpg and only looking at its exit status.  This has the downside that you do not get the reason for the failure.  If you were using GPGME (as recommended, see section " Programmatic use of GnuPG" in the GnuPG manual), you could easily distinguish certain cases, like this one:

```
$ python3 -c 'import gpg; gpg.Context().verify(open("tor-browser-linux64-6.0.5_en-US.tar.xz"), open("tor-browser-linux64-6.0.5_en-US.tar.xz.asc"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gpg/core.py", line 451, in verify
    raise errors.BadSignatures(result)
gpg.errors.BadSignatures: 2E1AC68ED40814E0: No public key
```

**Comment by Kajisav** [comment]
Been looking into doing this. PyME changed maintainers a few times and has since been merged into the GnuPG project's GPGME C library [here](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=tree;f=lang/python;hb=HEAD). I found relevant history [here](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=blob_plain;f=lang/python/docs/Short_History.rst;hb=HEAD) after looking for current PyME docs. Seems like documentation is limited to C but there are examples in python [here](https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=tree;f=lang/python/examples;hb=HEAD). Will report back when I have something to show.

**Comment by teythoon** [comment]
I'm the upstream maintainer of said bindings.  Feel free to poke me with questions.  Also, if there is anything missing in the bindings, I'd love to hear that as well.

Sorry for the missing documentation.  How we do documentation across different language bindings is an open question for now.

**Comment by dephekt** [comment]
@teythoon could you possibly show me an example showing how to access the libgpg-error library through the python bindings when one is called? Say I have the following:
```
with gpg.Context() as c:
        c.set_engine_info(gpg.constants.protocol.OpenPGP, '/usr/bin/gpg', gnupg_home)
        f = open(tor_browser_developers, 'r')
        keydata = f.read()
        c.op_import(keydata)
```
Then I want to handle errors like GPG_ERR_NO_ERROR or GPG_ERR_NO_DATA

**Comment by dephekt** [comment]
Hey folks, I have the replacement import_and_check_status function in common.py rewritten for gpgme [here](https://github.com/dephekt/torbrowser-launcher/blob/master/torbrowser_launcher/common.py#L187) if you'd like to make comments on things I should change early on.

I'm currently writing the verify function. @micahflee I'm curious how you would want to handle the issue 260/261 situations moving forward. If the signature fails because the public key was missing, should we try and obtain the key from somewhere? I'm trying to narrow the conditions where someone will see the "you are under attack" warning to exclude less hostile failures.

**Comment by dephekt** [comment]
@teythoon how can I differentiate between different types of BadSignature exceptions?

A missing public key:
```
raise errors.BadSignatures(result)
gpg.errors.BadSignatures: D1483FA6C3C07136: No public key
```
A failed to verify signature failure:
```
raise errors.BadSignatures(result)
gpg.errors.BadSignatures: D1483FA6C3C07136: Bad signature
```

I've tried different ways of finding where that message data is and am coming up empty.

**Comment by teythoon** [comment]
@dephekt sorry that the documentation is so sparse at the moment.  This is an open issue with the newly adopted bindings.

gpg.errors.BadSignatures is a complex error.  It has a 'result' field that is a list of objects describing the reason for the failure.  Every object in that list has a 'fpr' field with the signing keys fingerprint, and a 'status' field which is a GPGME status describing the reason for the failure.

The status codes have symbolic representations in the gpg.errors module:

```
In [6]: list(map(gpg.core.gpgme.gpgme_strerror, (gpg.errors.NO_PUBKEY, gpg.errors.BAD_SIGNATURE)))
Out[6]: ['No public key', 'Bad signature']
```

It is slightly weird, agreed, and suggestions to improve this would be helpful.  However, I don't see an easier solution, because different things can be wrong with different signatures at the same time, and one can only throw one error.

**Comment by dephekt** [comment]
Sorry for bothering you with that. I figured it out possibly 5 minutes after posting that last message.
```
           try:
                c.verify(signature=sig, signed_data=signed)
            except gpg.errors.BadSignatures as e:
                result = str(e).split(": ")
                if result[1] == 'Bad signature':
                    gui_raise_sigerror(self, str(e))
                elif result[1] == 'No public key':
                    gui_raise_sigerror(self, str(e))
```
