### ISSUE TITLE
On verification error, torbrowser-launcher should try refreshing gpg key

### ISSUE THREAD

**Issue by micahflee** [micahflee/torbrowser-launcher#271]
The last time torbrowser-launcher broke and started giving signature verification errors to everyone, it's because a new subkey was added to the Tor Browser Developers key. torbrowser-launcher should automatically check for this.

**Comment by dephekt** [comment]
I'll try and get a PR up for this before the end of next week.

On systems where the new GPG python bindings are available, we'll get the very specific key error to react to. On systems without the bindings, I think we'd just need to add a key refresh step in the current shell-out logic.

Is there a preference on where we ought to look to receive a key that is missing? E.g. just check a default key server or are the tor public keys located on a web server with a semi-permanent URL that we can just curl/wget and import?

**Comment by dephekt** [comment]
I propose:
- Defining a new method _refresh_keyring_ in the 'Common' class, which would contain logic to refresh the local homedir's keyring against whatever proposed key source(s) is decided upon. It will need to handle situations with and without GPGME binding sessions present.
- common.py: Add a call to _refresh_keyring_ in the _import_keys_ method, which is already executed every app run.
- launcher.py: (Optional) Also add a call to _Common_'s  _refresh_keyring_ method prior to executing a verify operations. (Although refreshing the keyring when the app started ought to have been enough).
- launcher.py: (Optional) Before raising _gui_raise_sigerror_ in the current shell-out logic in the _verify_ function, call _Commons_'s _refresh_keyring_ method before executing the verify shellcode.

This way, we make every effort to ensure the keyring is up-to-date prior to any verify operation. Then when we encounter a 'BadSignature' GPG exception, we can continue to throw a dialog to alert the user and offer to start-over.

The two optional notes above, I figure they're optional because running the app properly should always cause a keyring refresh in these circumstances, so doing it again before the verify would be superfluous unless there is some edge case I'm not considering.

**Comment by dephekt** [comment]
To refresh the keyring, I'm planning to do something like this:

```
    def refresh_keyring(self, fingerprint=None):
        if fingerprint is not None:
            p = subprocess.Popen(['/usr/bin/gpg', '--status-fd', '2',
                                  '--homedir', self.paths['gnupg_homedir'],
                                  '--keyserver', 'pool.sks-keyservers.net',
                                  '--recv-keys', fingerprint], stderr=subprocess.PIPE)

            for output in p.stderr.readlines():
                pass
        else:
            p = subprocess.Popen(['/usr/bin/gpg', '--status-fd', '2',
                                  '--homedir', self.paths['gnupg_homedir'],
                                  '--keyserver', 'pool.sks-keyservers.net',
                                  '--refresh-keys'], stderr=subprocess.PIPE)

            for output in p.stderr.readlines():
                pass
```
The first conditional will run if we have GPGME binding support and know the fingerprint of the key we are missing. In that case we run a _gpg --recv-keys_ operation against _pool.sks-keyservers.net_ using the fingerprint we passed from the verify exception.

If a fingerprint wasn't passed to our method, the second condition will run a more generic _gpg --refresh-keys_ operation against pool.sks-keyservers.net to try and refresh the whole local keyring.

Output checking I still need to write obviously. I just wanted to show a quick example of how I'm currently handling the key refresh.

FYI: There's no mechanism within the GPGME bindings to perform keyring refreshes or to obtain key files from a server, which is why I'm shelling out to GPG in both conditions above.

**Comment by dephekt** [comment]
Just for the sake of clarity, some updates from the PR: no longer performing ``--recv-keys`` operations for missing fingerprints due to security implications and all keyring refresh operations are being securely made via hkps.pool.sks-keyservers.net using a locally pinned CA for SSL verification.

The full command ran by GPG is something like this now:
````
gpg --homedir  ~/.local/share/tbb/torbrowser-launcher/gnupg_home
--keyserver hkps://hpks.pool.sks-keyservers.net
--keyserver-options ca-cert-file=/usr/share/torbrowser-launcher/sks-keyservers.netCA.pem
    ,include-revoked,no-honor-keyserver-url,no-honor-pka-record
--refresh-keys
````

If a completely new key fingerprint is encountered, we're still going to consider it a verify-failure so users can [verify trust](https://www.torproject.org/docs/signing-keys.html.en) of the new fingerprint out-of-band before manually importing the new key.
