### ISSUE TITLE
Command to download actual mirrrors for mirrors.txt 

### ISSUE THREAD

**Issue by merlinnusr** [micahflee/torbrowser-launcher#300]
`curl  https://www.torproject.org/getinvolved/mirrors.html.en -o mirror1.html  &&  cat mirror1.html | grep '<td><a href="https://' | grep -Eo "(https)://[a-zA-Z0-9./?=_-]*" | sort | uniq > mirrors.txt  
`
*it only create a file with https:// links 

if you have a better idea for the command.....

**Comment by merlinnusr** [comment]
curl https://www.torproject.org/getinvolved/mirrors.html.en -o mirror1.html && cat mirror1.html | grep '<td><a href="https://' | grep -Eo "(https)://[a-zA-Z0-9./?=_-]*/dist" | sort | uniq > mirrors.txt

I modify it in this  part ` grep -Eo "(https)://[a-zA-Z0-9./?=_-]*/dist" `

**Comment by micahflee** [comment]
I think trying to make torbrowser-launcher automatically download the list of mirrors probably isn't worth it, especially since a main reason to use a mirror is because torproject.org is being censored, so it likely wouldn't work anyway. I think just shipping updated lists of mirrors with torbrowser-launcher is a better plan.

Also, torproject.org could change the web design of that page at any moment and break things (in fact, I know they're about to launch a new design). But that said, cool command :).
