### ISSUE TITLE
Add obfuscation options

### ISSUE THREAD

**Issue by baimafeima** [micahflee/torbrowser-launcher#303]
Could you add obfuscation options when downloading and verifying Tor Browser via torbrowser-bundle? In censorship-affected areas (I am in China) the downloading process won't start unless you connect through another (insecure) VPN. It would be great to have obfs4 or ECC/XOR implemented in torbrowser-launcher.

**Comment by micahflee** [comment]
Tor Browser Launcher allows you to download Tor Browser over Tor, using a system Tor. So this is already possible, though slightly complicated. You just need to:

* Install system Tor
* Edit `/etc/tor/torrc` and configure use of a bridge with obfs4, and restart tor
* Run `torbrowser-launcher --settings` and say you want to use the system Tor

Trying to actually implement some sort of obfuscation directly into torbrowser-launcher isn't really practical because it just downloads the package from an https site, so I think users who want to do this should just run it through their system Tor.

**Comment by baimafeima** [comment]
@micahflee Unfortunately, this is way to complicated for me and any average user. Tor is especially needed in region where access to the Tor network is blocked and those users would have to rely on VPNs in order to install Tor on their system which isn't an ideal situation. Why would it be possible to implement obfs4 for the actual download process? Users could then tick a box in case they live in a censorship-affected area.
