### ISSUE TITLE
reports wrong version upon startup

### ISSUE THREAD

**Issue by taw00** [micahflee/torbrowser-launcher#315]
```
$ ./torbrowser-launcher-0.2.9/torbrowser-launcher 
Tor Browser Launcher
By Micah Lee, licensed under MIT
version 0.2.8
https://github.com/micahflee/torbrowser-launcher
Refreshing local keyring...
...etc...
```

**Comment by micahflee** [comment]
Ahh, this isn't actually a bug. This is because you have torbrowser-launcher 0.2.8 installed systemwide, and it's discovering the version from the file `/usr/share/torbrowser-launcher/version`. If you want it to use the local share folder, you need to execute like this:

`$ SHARE=./torbrowser-launcher-0.2.9/share ./torbrowser-launcher-0.2.9/torbrowser-launcher`
