### ISSUE TITLE
Please add option to choose language

### ISSUE THREAD

**Issue by ghost** [micahflee/torbrowser-launcher#345]
The Tor Browser is available in different languages, please make it possible to choose the language when installing the Tor Browser from torbrowser-launcher.

**Comment by micahflee** [comment]
It tries to automatically recognize your system's locale. Can you try again using torbrowser-launcher 0.3.0 and let me know if it doesn't automatically choose your language?

**Comment by jony0008** [comment]
@micahflee It works on 0.3.1

**Comment by rogers0** [comment]
@micahflee There's report that the new fix doesn't work.
- https://bugs.debian.org/753173#96

It's due to the commit:
- https://github.com/micahflee/torbrowser-launcher/commit/b828bdfafe60bb9bcf93ec660ad5c07ff7fdbdf5

And actually it reverted the original fix of this issue:
- https://github.com/micahflee/torbrowser-launcher/commit/7c896725304574052f3320d253c9c17c9794cd57

So please kindly revert again. Thank you!

**Comment by davidbaumann** [comment]
As the packages are language-generic now, this should be obsolete.
