### ISSUE TITLE
UNABLE TO UPDATE TOR BROWSER

### ISSUE THREAD

**Issue by vjohnk** [micahflee/torbrowser-launcher#346]
I GET AN ERROR 

Generic_Verify_Fail
![screenshot at 2018-09-10 20-58-54](https://user-images.githubusercontent.com/34914553/45307323-614e8080-b53c-11e8-8a52-9e4031053943.png)

I've tried redownloading the update by clicking on start button but the same error shows up
![screenshot at 2018-09-10 20-58-54](https://user-images.githubusercontent.com/34914553/45307375-9064f200-b53c-11e8-8390-1f1057bd8da9.png)

**Comment by vjohnk** [comment]
ERROR I GOT IT IS A PARROT OS after refresh gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --refresh-keys --keyserver pgp.mit.edu gpg: refreshing 1 key from hkp://pgp.mit.edu gpg: keyserver refresh failed: No dataUnable to Update Tor Browser

**Comment by micahflee** [comment]
This is fixed in the new version 0.3.0 that I just released. You can get it by either [installing from source](https://github.com/micahflee/torbrowser-launcher/blob/develop/BUILD.md) or installing from the Ubuntu PPA, described [here](https://github.com/micahflee/torbrowser-launcher/blob/develop/README.md#installing-in-ubuntu).
