### ISSUE TITLE
tor browser is not able to install on parrot security os.

### ISSUE THREAD

**Issue by kataria342** [micahflee/torbrowser-launcher#347]
Signature verification failed

ERROR Code:- GENERIC_VERIFY_FAIL

**Comment by micahflee** [comment]
This is fixed in the new version 0.3.0 that I just released. You can get it by either [installing from source](https://github.com/micahflee/torbrowser-launcher/blob/develop/BUILD.md) or installing from the Ubuntu PPA, described [here](https://github.com/micahflee/torbrowser-launcher/blob/develop/README.md#installing-in-ubuntu).
