### ISSUE TITLE
tor browser install failed

### ISSUE THREAD

**Issue by gstehr** [micahflee/torbrowser-launcher#429]
gpg: error writing keyring '/home/gstehr/.local/share/torbrowser/gnupg_homedir/pubring.kbx': Provided object is too large
signature verification failed

error code; GENERIC VERIFY _FAIL

lINUX MINT V19 Tara

**Comment by Gabmiral** [comment]
it's something no one can really change, the SKS keyserver system (which hosts almost every PGP public key) has recently been spammed and the keys that were the most used (important developpers and signing keys for software like Tor) have been flooded (by user certificates), making the key extremely big, and even too big for being able to

**Comment by Gabmiral** [comment]
It's something no one can really change, the SKS keyserver system (which hosts almost every PGP public key) has recently been spammed and the keys that were the most used (important developpers and signing keys for software like Tor) have been flooded (by user certificates), making the key too big for being used (it makes verification software crash or give up). Since Tor Browser Launcher **requires** the Tor Browser to be PGP Signed, it crashes.
