### ISSUE TITLE
Would it be possible to insert a "Global Dark" mode for the pages?

### ISSUE THREAD

**Issue by xzj8b3** [micahflee/torbrowser-launcher#445]
It would be really nice if it could be inserted in Torbrowser a mode "Global Dark" to make the pages dark thus avoiding installation of Stylus or similar extensions and load with it unverified external code .... I think the thing would be appreciated by many users especially by those who like me has problems with sensitivity to the eyes ....

An example could be the script I use currently with stylus that is really very restful for the view, but unfortunately you know these scripts often have problems with various services or are rarely updated!!
I hope my request can be taken into account, I leave below the link for example use with stylus so that it can be viewed.

https://userstyles.org/styles/170423/carbon-global-dark

**Comment by PlazmaKG** [comment]
This isn't the development of Tor Browser, this is just Tor Browser Launcher. You'd have to file a request for this to the actual Tor Project. That being said though, I highly doubt they would do this since, users who use dark pages, vs white, normal pages, give different fingerprints, which is what Tor Project develops Tor Browser to resist.
