### ISSUE TITLE
SIGNATURE VERIFICATION FAILED

### ISSUE THREAD

**Issue by HewmEvor** [micahflee/torbrowser-launcher#454]
Just following the instruction attached to failed verification to report this error here.
Process used (can be duplicated (many times))

1. Use sudo to install TOR
takes 10 minutes to start the d/l and install Launcher
2. Open Launcher, and 13 minutes to start d/l actual package.
3. .10 seconds to start Dl and install
4. Verifying starts, and 13 minutes later, the generic error pops open.

I have repeated the key resets, purge install, reboot, and then re-try.

This has been tried several times using different sites different suggestions - nothing has worked.

RIG:
Intel i3-3110M CPU@ 2.40GHZ
Memory 6G
Ubuntu 18.04.3 LTS

Tried install from:
Software Boutique
sudo app-get
github.com/micahflee/torbrowser-launcher/issues/

Yes - this may be "similar to 4 existing issues" but not same. - it seems that same matter with this issue.

**Comment by sajalmandrekar** [comment]
It may be due to your Tor being outdated. Try updating it and see if it works.This repository provides a latest version.
Run the following commands on terminal:

- sudo add-apt-repository ppa:micahflee/ppa
- sudo apt install torbrowser-launcher

Or check out this thread:
https://github.com/micahflee/torbrowser-launcher/issues/410
