### ISSUE TITLE
SIGNATURE VERIFICATION FAILED!

### ISSUE THREAD

**Issue by Erte01** [micahflee/torbrowser-launcher#497]
![Screenshot_2020-09-20_14-18-03](https://user-images.githubusercontent.com/71591370/93710071-51ff6600-fb4c-11ea-836e-cbe67e534cb4.png)

**Comment by joeljosephjin** [comment]
i too have the same problem

**Comment by joeljosephjin** [comment]
Found a solution here: #491 (comment)

**Comment by Capitalmind** [comment]
I have the same error code

**Comment by qorg11** [comment]
I fixed this by forcing the thing to import the `EB774491D9FF06E2` key.

`gpg --homedir ~/.local/share/torbrowser/gnupg_homedir --import EB774491D9FF06E2.asc`

That fixed the "Verification failed!" but now it says that I could be underattack because the tor browser version is older than it should ¯_(ツ)_/¯

I guess you can still use the torbrowser you installed via this by untaring the `~/.cache/torbrowser/download/tor-browser-linux64-10.0_en-US.tar.xz`

Apparently torbrowser-launcher deletes that file when closed, so rename it and untar it, then cd to the folder and `./start-tor-browser.desktop`

Or, more easily, download Tor Browser from https://torproject.org

@micahflee Please fix this. I don't expect my grandmother do to all of this.

>Found a solution here: #491 (comment)

This didn't work for me

**Comment by joshuaandrews63** [comment]
I have the same issue. It is very frustrating that I can't even launch my working version without it getting stuck in this broken update loop

**Comment by albin-antony** [comment]
Same for me. [this](https://github.com/micahflee/torbrowser-launcher/issues/491l) is not working for me.

**Comment by qorg11** [comment]
I made [this](https://github.com/qorg11/ebin-tor) as a temp solution. Only works in Linux

**Comment by joshuaandrews63** [comment]
I am running Fedora 31 and I would like to see micahflee fix the
torbrowser-launcher as it is part of the distribution.

Thank you

**Comment by sburris0** [comment]
I'm seeing this on up-to-date Void Linux also

**Comment by KazashimoN** [comment]
I can see this issue too on Linux Mint 19.3 Cinnamon. The above solutions have not resolved the issue.

**Comment by drzraf** [comment]
Alternative suggestion:
` curl -s https://openpgpkey.torproject.org/.well-known/openpgpkey/torproject.org/hu/kounek7zrdx745qydx6p59t9mqjpuhdf | gpg --import --homedir .local/share/torbrowser/gnupg_homedir/ -`
(as per https://support.torproject.org/tbb/how-to-verify-signature/)
