### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by michal25** [micahflee/torbrowser-launcher#530]
The problem is not solved, yet.

Here is an fresh installation of torbrowser-launcher for 
https://github.com/micahflee/torbrowser-launcher

![Screenshot_20201007_140121](https://user-images.githubusercontent.com/5064337/95329922-079a1b00-08a8-11eb-9ee2-66f5c243b381.png)

And the problem with not valid key remains.

**Comment by michal25** [comment]
But, the manual installation (tar.gz) works
https://www.howtogeek.com/423866/how-to-install-and-use-the-tor-browser-on-linux/

**Comment by beauxq** [comment]
I'm not getting "signature verification failed".
I'm getting stuck on "verifying signature" forever.

**Comment by micahflee** [comment]
This is fixed in the newest version.

I just discontinued publishing torbrowser-launcher from the PPA, and instead you can get the newest version from Flatpak.

Uninstall it with:

```
sudo apt remove torbrowser-launcher
```

Then reinstall it from the Flatpak package here: https://flathub.org/apps/details/com.github.micahflee.torbrowser-launcher
