### ISSUE TITLE
torbrowser-launcher not working correctly in kali-linux

### ISSUE THREAD

**Issue by mairi88** [micahflee/torbrowser-launcher#633]
SIGNATURE VERIFICATION FAILED!
I face this Error Code: E53D989A9E2D47B
![Screenshot from 2022-04-15 20-57-38](https://user-images.githubusercontent.com/60855487/163593161-29291595-58fb-48e4-a47e-7957c388bce6.png)
F

**Comment by u451f** [comment]
E53D989A9E2D47B is not an error code but it's the ID of the OpenPGP key of the torbrowser developers, key which is used to verify that the package you downloaded is intact and authentic. The error message you see is pretty clear:

1. You might be under attack,
2. there might be a network problem, or 
3. you may be missing a recently added Tor Browser verification key.

As far as I know, reinstalling torbrowser using the torbrowser-launcher, it will normally refresh your GPG keyring automatically. 

Why are you using torbrowser-launcher at all instead of installing torbrowser directly from the torproject website? The only difference is that torbrowser-launcher provides AppArmor policies which enhance security, but only if AppArmor is also enabled on your machine. Probably Kali Linux does enable it by default.

I'm also wondering, if you don't know OpenPGP why are you using Kali Linux, as it's a distribution aimed at hacking and pentesting? Anyway, you need to read the error messages and then rule out each of the three options above. Likely, as many others reporting errors with the key it's just not up-to-date on your system. Check:

`gpg --list-keys torbrowser@torproject.org`

You should see something like that:

```
pub   rsa4096/0x4E2C6E8793298290 2014-12-15 [C] [verfällt: 2025-07-21]
  Schl.-Fingerabdruck = EF6E 286D DA85 EA2A 4BA7  DE68 4E2C 6E87 9329 8290
uid                [ unbekannt ] Tor Browser Developers (signing key) <torbrowser@torproject.org>
sub   rsa4096/0xE53D989A9E2D47BF 2021-09-17 [S] [verfällt: 2023-09-17]
```
