### ISSUE TITLE
torbrowser-launcher small bug

### ISSUE THREAD

**Issue by djurjo** [micahflee/torbrowser-launcher#636]
Hi,  I found a small bug at [__init__.py](https://github.com/micahflee/torbrowser-launcher/blob/develop/torbrowser_launcher/__init__.py) lines 92-95.
It seems that `gui.move(_, _)` can only get integers but the operations `(desktop.width() - window_size.width()) / 2` and `(desktop.height() - window_size.height()) / 2` can return a floating point number raising an error while running the launcher.
A simple solution which I made in my installation is changing the operator / -> // .

hope it helps, thanks for your work !!

bests

**Comment by u451f** [comment]
See #599 and #628

**Comment by djurjo** [comment]
Thanks :)

**Comment by siriusstar2007** [comment]
Hello,

How do I open the file init.py to modify it?

Thank you!

**Comment by siriusstar2007** [comment]
I managed to open the _init_.py file with the Qt Creator application but I can't save the changes I made because I don't have the permission.
Should I open the _init_.py file in root mode and if so, how should I do?

Thanks a lot!

**Comment by jardasmahel** [comment]
@siriusstar2007 You can open it in nano or sublime text or any text editor. This bug is in Ubuntu so I assume you have linux.
It needed root permission to modify it so just put sudo in front of that command.
So do something like 
`sudo nano /usr/lib/python3/dist-packages/torbrowser_launcher/__init__.py`
Be careful with sudo command tho!
